# Makefile.in generated by automake 1.9.6 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005  Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




srcdir = .
top_srcdir = .

pkgdatadir = $(datadir)/simdock
pkglibdir = $(libdir)/simdock
pkgincludedir = $(includedir)/simdock
top_builddir = .
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
INSTALL = /usr/bin/install -c
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = simdock$(EXEEXT)
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(top_srcdir)/configure AUTHORS COPYING ChangeLog INSTALL NEWS \
	TODO config.guess config.sub depcomp install-sh ltmain.sh \
	missing mkinstalldirs
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/acinclude.m4 \
	$(top_srcdir)/wxwin.m4 $(top_srcdir)/pkg.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno configure.status.lineno
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(simdockBGSdir)" \
	"$(DESTDIR)$(simdockDESKTOPdir)" "$(DESTDIR)$(simdockICONdir)"
binPROGRAMS_INSTALL = $(INSTALL_PROGRAM)
PROGRAMS = $(bin_PROGRAMS)
am_simdock_OBJECTS = background.$(OBJEXT) \
	save_launchers.$(OBJEXT) sim_gconf.$(OBJEXT) xstuff.$(OBJEXT) \
	interrupts.$(OBJEXT) main_arguments.$(OBJEXT) \
	main_settings.$(OBJEXT) settingsDialog.$(OBJEXT) \
	tasks.$(OBJEXT) gconf_settings.$(OBJEXT) \
	launcher_dialog.$(OBJEXT) main.$(OBJEXT) simImage.$(OBJEXT) \
	myFrame.$(OBJEXT)
simdock_OBJECTS = $(am_simdock_OBJECTS)
am__DEPENDENCIES_1 =
simdock_DEPENDENCIES = $(am__DEPENDENCIES_1)
DEFAULT_INCLUDES = -I. -I$(srcdir) -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
SOURCES = $(simdock_SOURCES)
DIST_SOURCES = $(simdock_SOURCES)
RECURSIVE_TARGETS = all-recursive check-recursive dvi-recursive \
	html-recursive info-recursive install-data-recursive \
	install-exec-recursive install-info-recursive \
	install-recursive installcheck-recursive installdirs-recursive \
	pdf-recursive ps-recursive uninstall-info-recursive \
	uninstall-recursive
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = `echo $$p | sed -e 's|^.*/||'`;
simdockBGSDATA_INSTALL = $(INSTALL_DATA)
simdockDESKTOPDATA_INSTALL = $(INSTALL_DATA)
simdockICONDATA_INSTALL = $(INSTALL_DATA)
DATA = $(simdockBGS_DATA) $(simdockDESKTOP_DATA) $(simdockICON_DATA)
ETAGS = etags
CTAGS = ctags
DIST_SUBDIRS = $(SUBDIRS)
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d $(distdir) \
    || { find $(distdir) -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr $(distdir); }; }
DIST_ARCHIVES = $(distdir).tar.gz $(distdir).tar.bz2
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/onli/scripts/simdock_sources/unstable/missing --run aclocal-1.9
AMDEP_FALSE = #
AMDEP_TRUE = 
AMTAR = ${SHELL} /home/onli/scripts/simdock_sources/unstable/missing --run tar
AUTOCONF = ${SHELL} /home/onli/scripts/simdock_sources/unstable/missing --run autoconf
AUTOHEADER = ${SHELL} /home/onli/scripts/simdock_sources/unstable/missing --run autoheader
AUTOMAKE = ${SHELL} /home/onli/scripts/simdock_sources/unstable/missing --run automake-1.9
AWK = mawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS =  -DORBIT2=1 -pthread -D_REENTRANT -I/usr/include/gconf/2 -I/usr/include/orbit-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libwnck-1.0 -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/startup-notification-1.0 -I/usr/include/gtk-2.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/directfb -I/usr/include/libpng12 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/gio-unix-2.0/   -I/usr/lib/wx/include/gtk2-unicode-release-2.8 -I/usr/include/wx-2.8 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXGTK__ 
CXX = g++
CXXDEPMODE = depmode=gcc3
CXXFLAGS =  -DORBIT2=1 -pthread -D_REENTRANT -I/usr/include/gconf/2 -I/usr/include/orbit-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libwnck-1.0 -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/startup-notification-1.0 -I/usr/include/gtk-2.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/directfb -I/usr/include/libpng12 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/gio-unix-2.0/   -I/usr/lib/wx/include/gtk2-unicode-release-2.8 -I/usr/include/wx-2.8 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXGTK__
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DEPS_CFLAGS = -DORBIT2=1 -pthread -D_REENTRANT -I/usr/include/gconf/2 -I/usr/include/orbit-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libwnck-1.0 -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/startup-notification-1.0 -I/usr/include/gtk-2.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/directfb -I/usr/include/libpng12 -I/usr/lib/gtk-2.0/include -I/usr/include/atk-1.0 -I/usr/include/gio-unix-2.0/  
DEPS_LIBS = -pthread -lgconf-2 -lwnck-1 -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lgdk_pixbuf-2.0 -lm -lpangocairo-1.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0  
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
GCONF_REQUIRED = 2.18.0
GREP = /bin/grep
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = -pthread -lgconf-2 -lwnck-1 -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lgdk_pixbuf-2.0 -lm -lpangocairo-1.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0   -pthread -Wl,-Bsymbolic-functions  -lwx_gtk2u_richtext-2.8 -lwx_gtk2u_aui-2.8 -lwx_gtk2u_xrc-2.8 -lwx_gtk2u_qa-2.8 -lwx_gtk2u_html-2.8 -lwx_gtk2u_adv-2.8 -lwx_gtk2u_core-2.8 -lwx_baseu_xml-2.8 -lwx_baseu_net-2.8 -lwx_baseu-2.8 
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/onli/scripts/simdock_sources/unstable/missing --run makeinfo
OBJEXT = o
PACKAGE = simdock
PACKAGE_BUGREPORT = simonedll@yahoo.it
PACKAGE_NAME = simdock
PACKAGE_STRING = simdock 1.2
PACKAGE_TARNAME = simdock
PACKAGE_VERSION = 1.2
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
RANLIB = ranlib
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
VERSION = 1.2
WNCK_REQUIRED = 2.18.0
WX_CFLAGS = -I/usr/lib/wx/include/gtk2-unicode-release-2.8 -I/usr/include/wx-2.8 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXGTK__ -pthread
WX_CFLAGS_ONLY = -pthread
WX_CONFIG_PATH = /usr/bin/wx-config
WX_CPPFLAGS = -I/usr/lib/wx/include/gtk2-unicode-release-2.8 -I/usr/include/wx-2.8 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXGTK__
WX_CXXFLAGS = -I/usr/lib/wx/include/gtk2-unicode-release-2.8 -I/usr/include/wx-2.8 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXGTK__ -pthread
WX_CXXFLAGS_ONLY = 
WX_LIBS = -pthread -Wl,-Bsymbolic-functions  -lwx_gtk2u_richtext-2.8 -lwx_gtk2u_aui-2.8 -lwx_gtk2u_xrc-2.8 -lwx_gtk2u_qa-2.8 -lwx_gtk2u_html-2.8 -lwx_gtk2u_adv-2.8 -lwx_gtk2u_core-2.8 -lwx_baseu_xml-2.8 -lwx_baseu_net-2.8 -lwx_baseu-2.8 
WX_LIBS_STATIC = 
WX_VERSION = 2.8.10
ac_ct_CC = gcc
ac_ct_CXX = g++
am__fastdepCC_FALSE = #
am__fastdepCC_TRUE = 
am__fastdepCXX_FALSE = #
am__fastdepCXX_TRUE = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build_alias = 
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = /home/onli/scripts/simdock_sources/unstable/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = mkdir -p --
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
sysconfdir = ${prefix}/etc
target_alias = 
SUBDIRS = po src
#simdock_LDADD = -pthread -lgconf-2 -lwnck-1 -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lgdk_pixbuf-2.0 -lm -lpangocairo-1.0 -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0   -pthread -Wl,-Bsymbolic-functions  -lwx_gtk2u_richtext-2.8 -lwx_gtk2u_aui-2.8 -lwx_gtk2u_xrc-2.8 -lwx_gtk2u_qa-2.8 -lwx_gtk2u_html-2.8 -lwx_gtk2u_adv-2.8 -lwx_gtk2u_core-2.8 -lwx_baseu_xml-2.8 -lwx_baseu_net-2.8 -lwx_baseu-2.8  #$(WX_LIBS)
simdock_LDFLAGS = $(LDFLAGS)
simdock_LDADD = $(LIBS)
simdock_SOURCES = src/background.cc src/save_launchers.cc src/sim_gconf.cc src/xstuff.cc src/interrupts.cc src/main_arguments.cc src/main_settings.cc src/settingsDialog.cc src/tasks.cc src/gconf_settings.cc src/launcher_dialog.cc src/main.cc src/simImage.cc src/myFrame.cc
simdockBGSdir = /usr/share/simdock
simdockBGS_DATA = src/bg.png src/bg2.png src/bg5.png src/mark.png src/question.png
simdockDESKTOPdir = /usr/share/applications
simdockDESKTOP_DATA = simdock.desktop
simdockICONdir = /usr/share/pixmaps
simdockICON_DATA = simdock.png
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-recursive

.SUFFIXES:
.SUFFIXES: .cc .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu '; \
	      cd $(srcdir) && $(AUTOMAKE) --gnu  \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu  Makefile'; \
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)

config.h: stamp-h1
	@if test ! -f $@; then \
	  rm -f stamp-h1; \
	  $(MAKE) stamp-h1; \
	else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	cd $(top_srcdir) && $(AUTOHEADER)
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(mkdir_p) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	  ; then \
	    f=`echo "$$p1" | sed 's,^.*/,,;$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(binPROGRAMS_INSTALL) '$$p' '$(DESTDIR)$(bindir)/$$f'"; \
	   $(INSTALL_PROGRAM_ENV) $(binPROGRAMS_INSTALL) "$$p" "$(DESTDIR)$(bindir)/$$f" || exit 1; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo "$$p" | sed 's,^.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f '$(DESTDIR)$(bindir)/$$f'"; \
	  rm -f "$(DESTDIR)$(bindir)/$$f"; \
	done

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
simdock$(EXEEXT): $(simdock_OBJECTS) $(simdock_DEPENDENCIES) 
	@rm -f simdock$(EXEEXT)
	$(CXXLINK) $(simdock_LDFLAGS) $(simdock_OBJECTS) $(simdock_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/background.Po
include ./$(DEPDIR)/gconf_settings.Po
include ./$(DEPDIR)/interrupts.Po
include ./$(DEPDIR)/launcher_dialog.Po
include ./$(DEPDIR)/main.Po
include ./$(DEPDIR)/main_arguments.Po
include ./$(DEPDIR)/main_settings.Po
include ./$(DEPDIR)/myFrame.Po
include ./$(DEPDIR)/save_launchers.Po
include ./$(DEPDIR)/settingsDialog.Po
include ./$(DEPDIR)/simImage.Po
include ./$(DEPDIR)/sim_gconf.Po
include ./$(DEPDIR)/tasks.Po
include ./$(DEPDIR)/xstuff.Po

.cc.o:
	if $(CXXCOMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" -c -o $@ $<; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; fi
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cc.obj:
	if $(CXXCOMPILE) -MT $@ -MD -MP -MF "$(DEPDIR)/$*.Tpo" -c -o $@ `$(CYGPATH_W) '$<'`; \
	then mv -f "$(DEPDIR)/$*.Tpo" "$(DEPDIR)/$*.Po"; else rm -f "$(DEPDIR)/$*.Tpo"; exit 1; fi
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

background.o: src/background.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT background.o -MD -MP -MF "$(DEPDIR)/background.Tpo" -c -o background.o `test -f 'src/background.cc' || echo '$(srcdir)/'`src/background.cc; \
	then mv -f "$(DEPDIR)/background.Tpo" "$(DEPDIR)/background.Po"; else rm -f "$(DEPDIR)/background.Tpo"; exit 1; fi
#	source='src/background.cc' object='background.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o background.o `test -f 'src/background.cc' || echo '$(srcdir)/'`src/background.cc

background.obj: src/background.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT background.obj -MD -MP -MF "$(DEPDIR)/background.Tpo" -c -o background.obj `if test -f 'src/background.cc'; then $(CYGPATH_W) 'src/background.cc'; else $(CYGPATH_W) '$(srcdir)/src/background.cc'; fi`; \
	then mv -f "$(DEPDIR)/background.Tpo" "$(DEPDIR)/background.Po"; else rm -f "$(DEPDIR)/background.Tpo"; exit 1; fi
#	source='src/background.cc' object='background.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o background.obj `if test -f 'src/background.cc'; then $(CYGPATH_W) 'src/background.cc'; else $(CYGPATH_W) '$(srcdir)/src/background.cc'; fi`

save_launchers.o: src/save_launchers.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT save_launchers.o -MD -MP -MF "$(DEPDIR)/save_launchers.Tpo" -c -o save_launchers.o `test -f 'src/save_launchers.cc' || echo '$(srcdir)/'`src/save_launchers.cc; \
	then mv -f "$(DEPDIR)/save_launchers.Tpo" "$(DEPDIR)/save_launchers.Po"; else rm -f "$(DEPDIR)/save_launchers.Tpo"; exit 1; fi
#	source='src/save_launchers.cc' object='save_launchers.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o save_launchers.o `test -f 'src/save_launchers.cc' || echo '$(srcdir)/'`src/save_launchers.cc

save_launchers.obj: src/save_launchers.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT save_launchers.obj -MD -MP -MF "$(DEPDIR)/save_launchers.Tpo" -c -o save_launchers.obj `if test -f 'src/save_launchers.cc'; then $(CYGPATH_W) 'src/save_launchers.cc'; else $(CYGPATH_W) '$(srcdir)/src/save_launchers.cc'; fi`; \
	then mv -f "$(DEPDIR)/save_launchers.Tpo" "$(DEPDIR)/save_launchers.Po"; else rm -f "$(DEPDIR)/save_launchers.Tpo"; exit 1; fi
#	source='src/save_launchers.cc' object='save_launchers.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o save_launchers.obj `if test -f 'src/save_launchers.cc'; then $(CYGPATH_W) 'src/save_launchers.cc'; else $(CYGPATH_W) '$(srcdir)/src/save_launchers.cc'; fi`

sim_gconf.o: src/sim_gconf.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sim_gconf.o -MD -MP -MF "$(DEPDIR)/sim_gconf.Tpo" -c -o sim_gconf.o `test -f 'src/sim_gconf.cc' || echo '$(srcdir)/'`src/sim_gconf.cc; \
	then mv -f "$(DEPDIR)/sim_gconf.Tpo" "$(DEPDIR)/sim_gconf.Po"; else rm -f "$(DEPDIR)/sim_gconf.Tpo"; exit 1; fi
#	source='src/sim_gconf.cc' object='sim_gconf.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sim_gconf.o `test -f 'src/sim_gconf.cc' || echo '$(srcdir)/'`src/sim_gconf.cc

sim_gconf.obj: src/sim_gconf.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sim_gconf.obj -MD -MP -MF "$(DEPDIR)/sim_gconf.Tpo" -c -o sim_gconf.obj `if test -f 'src/sim_gconf.cc'; then $(CYGPATH_W) 'src/sim_gconf.cc'; else $(CYGPATH_W) '$(srcdir)/src/sim_gconf.cc'; fi`; \
	then mv -f "$(DEPDIR)/sim_gconf.Tpo" "$(DEPDIR)/sim_gconf.Po"; else rm -f "$(DEPDIR)/sim_gconf.Tpo"; exit 1; fi
#	source='src/sim_gconf.cc' object='sim_gconf.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sim_gconf.obj `if test -f 'src/sim_gconf.cc'; then $(CYGPATH_W) 'src/sim_gconf.cc'; else $(CYGPATH_W) '$(srcdir)/src/sim_gconf.cc'; fi`

xstuff.o: src/xstuff.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT xstuff.o -MD -MP -MF "$(DEPDIR)/xstuff.Tpo" -c -o xstuff.o `test -f 'src/xstuff.cc' || echo '$(srcdir)/'`src/xstuff.cc; \
	then mv -f "$(DEPDIR)/xstuff.Tpo" "$(DEPDIR)/xstuff.Po"; else rm -f "$(DEPDIR)/xstuff.Tpo"; exit 1; fi
#	source='src/xstuff.cc' object='xstuff.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o xstuff.o `test -f 'src/xstuff.cc' || echo '$(srcdir)/'`src/xstuff.cc

xstuff.obj: src/xstuff.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT xstuff.obj -MD -MP -MF "$(DEPDIR)/xstuff.Tpo" -c -o xstuff.obj `if test -f 'src/xstuff.cc'; then $(CYGPATH_W) 'src/xstuff.cc'; else $(CYGPATH_W) '$(srcdir)/src/xstuff.cc'; fi`; \
	then mv -f "$(DEPDIR)/xstuff.Tpo" "$(DEPDIR)/xstuff.Po"; else rm -f "$(DEPDIR)/xstuff.Tpo"; exit 1; fi
#	source='src/xstuff.cc' object='xstuff.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o xstuff.obj `if test -f 'src/xstuff.cc'; then $(CYGPATH_W) 'src/xstuff.cc'; else $(CYGPATH_W) '$(srcdir)/src/xstuff.cc'; fi`

interrupts.o: src/interrupts.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT interrupts.o -MD -MP -MF "$(DEPDIR)/interrupts.Tpo" -c -o interrupts.o `test -f 'src/interrupts.cc' || echo '$(srcdir)/'`src/interrupts.cc; \
	then mv -f "$(DEPDIR)/interrupts.Tpo" "$(DEPDIR)/interrupts.Po"; else rm -f "$(DEPDIR)/interrupts.Tpo"; exit 1; fi
#	source='src/interrupts.cc' object='interrupts.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o interrupts.o `test -f 'src/interrupts.cc' || echo '$(srcdir)/'`src/interrupts.cc

interrupts.obj: src/interrupts.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT interrupts.obj -MD -MP -MF "$(DEPDIR)/interrupts.Tpo" -c -o interrupts.obj `if test -f 'src/interrupts.cc'; then $(CYGPATH_W) 'src/interrupts.cc'; else $(CYGPATH_W) '$(srcdir)/src/interrupts.cc'; fi`; \
	then mv -f "$(DEPDIR)/interrupts.Tpo" "$(DEPDIR)/interrupts.Po"; else rm -f "$(DEPDIR)/interrupts.Tpo"; exit 1; fi
#	source='src/interrupts.cc' object='interrupts.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o interrupts.obj `if test -f 'src/interrupts.cc'; then $(CYGPATH_W) 'src/interrupts.cc'; else $(CYGPATH_W) '$(srcdir)/src/interrupts.cc'; fi`

main_arguments.o: src/main_arguments.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT main_arguments.o -MD -MP -MF "$(DEPDIR)/main_arguments.Tpo" -c -o main_arguments.o `test -f 'src/main_arguments.cc' || echo '$(srcdir)/'`src/main_arguments.cc; \
	then mv -f "$(DEPDIR)/main_arguments.Tpo" "$(DEPDIR)/main_arguments.Po"; else rm -f "$(DEPDIR)/main_arguments.Tpo"; exit 1; fi
#	source='src/main_arguments.cc' object='main_arguments.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o main_arguments.o `test -f 'src/main_arguments.cc' || echo '$(srcdir)/'`src/main_arguments.cc

main_arguments.obj: src/main_arguments.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT main_arguments.obj -MD -MP -MF "$(DEPDIR)/main_arguments.Tpo" -c -o main_arguments.obj `if test -f 'src/main_arguments.cc'; then $(CYGPATH_W) 'src/main_arguments.cc'; else $(CYGPATH_W) '$(srcdir)/src/main_arguments.cc'; fi`; \
	then mv -f "$(DEPDIR)/main_arguments.Tpo" "$(DEPDIR)/main_arguments.Po"; else rm -f "$(DEPDIR)/main_arguments.Tpo"; exit 1; fi
#	source='src/main_arguments.cc' object='main_arguments.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o main_arguments.obj `if test -f 'src/main_arguments.cc'; then $(CYGPATH_W) 'src/main_arguments.cc'; else $(CYGPATH_W) '$(srcdir)/src/main_arguments.cc'; fi`

main_settings.o: src/main_settings.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT main_settings.o -MD -MP -MF "$(DEPDIR)/main_settings.Tpo" -c -o main_settings.o `test -f 'src/main_settings.cc' || echo '$(srcdir)/'`src/main_settings.cc; \
	then mv -f "$(DEPDIR)/main_settings.Tpo" "$(DEPDIR)/main_settings.Po"; else rm -f "$(DEPDIR)/main_settings.Tpo"; exit 1; fi
#	source='src/main_settings.cc' object='main_settings.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o main_settings.o `test -f 'src/main_settings.cc' || echo '$(srcdir)/'`src/main_settings.cc

main_settings.obj: src/main_settings.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT main_settings.obj -MD -MP -MF "$(DEPDIR)/main_settings.Tpo" -c -o main_settings.obj `if test -f 'src/main_settings.cc'; then $(CYGPATH_W) 'src/main_settings.cc'; else $(CYGPATH_W) '$(srcdir)/src/main_settings.cc'; fi`; \
	then mv -f "$(DEPDIR)/main_settings.Tpo" "$(DEPDIR)/main_settings.Po"; else rm -f "$(DEPDIR)/main_settings.Tpo"; exit 1; fi
#	source='src/main_settings.cc' object='main_settings.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o main_settings.obj `if test -f 'src/main_settings.cc'; then $(CYGPATH_W) 'src/main_settings.cc'; else $(CYGPATH_W) '$(srcdir)/src/main_settings.cc'; fi`

settingsDialog.o: src/settingsDialog.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT settingsDialog.o -MD -MP -MF "$(DEPDIR)/settingsDialog.Tpo" -c -o settingsDialog.o `test -f 'src/settingsDialog.cc' || echo '$(srcdir)/'`src/settingsDialog.cc; \
	then mv -f "$(DEPDIR)/settingsDialog.Tpo" "$(DEPDIR)/settingsDialog.Po"; else rm -f "$(DEPDIR)/settingsDialog.Tpo"; exit 1; fi
#	source='src/settingsDialog.cc' object='settingsDialog.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o settingsDialog.o `test -f 'src/settingsDialog.cc' || echo '$(srcdir)/'`src/settingsDialog.cc

settingsDialog.obj: src/settingsDialog.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT settingsDialog.obj -MD -MP -MF "$(DEPDIR)/settingsDialog.Tpo" -c -o settingsDialog.obj `if test -f 'src/settingsDialog.cc'; then $(CYGPATH_W) 'src/settingsDialog.cc'; else $(CYGPATH_W) '$(srcdir)/src/settingsDialog.cc'; fi`; \
	then mv -f "$(DEPDIR)/settingsDialog.Tpo" "$(DEPDIR)/settingsDialog.Po"; else rm -f "$(DEPDIR)/settingsDialog.Tpo"; exit 1; fi
#	source='src/settingsDialog.cc' object='settingsDialog.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o settingsDialog.obj `if test -f 'src/settingsDialog.cc'; then $(CYGPATH_W) 'src/settingsDialog.cc'; else $(CYGPATH_W) '$(srcdir)/src/settingsDialog.cc'; fi`

tasks.o: src/tasks.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT tasks.o -MD -MP -MF "$(DEPDIR)/tasks.Tpo" -c -o tasks.o `test -f 'src/tasks.cc' || echo '$(srcdir)/'`src/tasks.cc; \
	then mv -f "$(DEPDIR)/tasks.Tpo" "$(DEPDIR)/tasks.Po"; else rm -f "$(DEPDIR)/tasks.Tpo"; exit 1; fi
#	source='src/tasks.cc' object='tasks.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o tasks.o `test -f 'src/tasks.cc' || echo '$(srcdir)/'`src/tasks.cc

tasks.obj: src/tasks.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT tasks.obj -MD -MP -MF "$(DEPDIR)/tasks.Tpo" -c -o tasks.obj `if test -f 'src/tasks.cc'; then $(CYGPATH_W) 'src/tasks.cc'; else $(CYGPATH_W) '$(srcdir)/src/tasks.cc'; fi`; \
	then mv -f "$(DEPDIR)/tasks.Tpo" "$(DEPDIR)/tasks.Po"; else rm -f "$(DEPDIR)/tasks.Tpo"; exit 1; fi
#	source='src/tasks.cc' object='tasks.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o tasks.obj `if test -f 'src/tasks.cc'; then $(CYGPATH_W) 'src/tasks.cc'; else $(CYGPATH_W) '$(srcdir)/src/tasks.cc'; fi`

gconf_settings.o: src/gconf_settings.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT gconf_settings.o -MD -MP -MF "$(DEPDIR)/gconf_settings.Tpo" -c -o gconf_settings.o `test -f 'src/gconf_settings.cc' || echo '$(srcdir)/'`src/gconf_settings.cc; \
	then mv -f "$(DEPDIR)/gconf_settings.Tpo" "$(DEPDIR)/gconf_settings.Po"; else rm -f "$(DEPDIR)/gconf_settings.Tpo"; exit 1; fi
#	source='src/gconf_settings.cc' object='gconf_settings.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o gconf_settings.o `test -f 'src/gconf_settings.cc' || echo '$(srcdir)/'`src/gconf_settings.cc

gconf_settings.obj: src/gconf_settings.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT gconf_settings.obj -MD -MP -MF "$(DEPDIR)/gconf_settings.Tpo" -c -o gconf_settings.obj `if test -f 'src/gconf_settings.cc'; then $(CYGPATH_W) 'src/gconf_settings.cc'; else $(CYGPATH_W) '$(srcdir)/src/gconf_settings.cc'; fi`; \
	then mv -f "$(DEPDIR)/gconf_settings.Tpo" "$(DEPDIR)/gconf_settings.Po"; else rm -f "$(DEPDIR)/gconf_settings.Tpo"; exit 1; fi
#	source='src/gconf_settings.cc' object='gconf_settings.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o gconf_settings.obj `if test -f 'src/gconf_settings.cc'; then $(CYGPATH_W) 'src/gconf_settings.cc'; else $(CYGPATH_W) '$(srcdir)/src/gconf_settings.cc'; fi`

launcher_dialog.o: src/launcher_dialog.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT launcher_dialog.o -MD -MP -MF "$(DEPDIR)/launcher_dialog.Tpo" -c -o launcher_dialog.o `test -f 'src/launcher_dialog.cc' || echo '$(srcdir)/'`src/launcher_dialog.cc; \
	then mv -f "$(DEPDIR)/launcher_dialog.Tpo" "$(DEPDIR)/launcher_dialog.Po"; else rm -f "$(DEPDIR)/launcher_dialog.Tpo"; exit 1; fi
#	source='src/launcher_dialog.cc' object='launcher_dialog.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o launcher_dialog.o `test -f 'src/launcher_dialog.cc' || echo '$(srcdir)/'`src/launcher_dialog.cc

launcher_dialog.obj: src/launcher_dialog.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT launcher_dialog.obj -MD -MP -MF "$(DEPDIR)/launcher_dialog.Tpo" -c -o launcher_dialog.obj `if test -f 'src/launcher_dialog.cc'; then $(CYGPATH_W) 'src/launcher_dialog.cc'; else $(CYGPATH_W) '$(srcdir)/src/launcher_dialog.cc'; fi`; \
	then mv -f "$(DEPDIR)/launcher_dialog.Tpo" "$(DEPDIR)/launcher_dialog.Po"; else rm -f "$(DEPDIR)/launcher_dialog.Tpo"; exit 1; fi
#	source='src/launcher_dialog.cc' object='launcher_dialog.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o launcher_dialog.obj `if test -f 'src/launcher_dialog.cc'; then $(CYGPATH_W) 'src/launcher_dialog.cc'; else $(CYGPATH_W) '$(srcdir)/src/launcher_dialog.cc'; fi`

main.o: src/main.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT main.o -MD -MP -MF "$(DEPDIR)/main.Tpo" -c -o main.o `test -f 'src/main.cc' || echo '$(srcdir)/'`src/main.cc; \
	then mv -f "$(DEPDIR)/main.Tpo" "$(DEPDIR)/main.Po"; else rm -f "$(DEPDIR)/main.Tpo"; exit 1; fi
#	source='src/main.cc' object='main.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o main.o `test -f 'src/main.cc' || echo '$(srcdir)/'`src/main.cc

main.obj: src/main.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT main.obj -MD -MP -MF "$(DEPDIR)/main.Tpo" -c -o main.obj `if test -f 'src/main.cc'; then $(CYGPATH_W) 'src/main.cc'; else $(CYGPATH_W) '$(srcdir)/src/main.cc'; fi`; \
	then mv -f "$(DEPDIR)/main.Tpo" "$(DEPDIR)/main.Po"; else rm -f "$(DEPDIR)/main.Tpo"; exit 1; fi
#	source='src/main.cc' object='main.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o main.obj `if test -f 'src/main.cc'; then $(CYGPATH_W) 'src/main.cc'; else $(CYGPATH_W) '$(srcdir)/src/main.cc'; fi`

simImage.o: src/simImage.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT simImage.o -MD -MP -MF "$(DEPDIR)/simImage.Tpo" -c -o simImage.o `test -f 'src/simImage.cc' || echo '$(srcdir)/'`src/simImage.cc; \
	then mv -f "$(DEPDIR)/simImage.Tpo" "$(DEPDIR)/simImage.Po"; else rm -f "$(DEPDIR)/simImage.Tpo"; exit 1; fi
#	source='src/simImage.cc' object='simImage.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o simImage.o `test -f 'src/simImage.cc' || echo '$(srcdir)/'`src/simImage.cc

simImage.obj: src/simImage.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT simImage.obj -MD -MP -MF "$(DEPDIR)/simImage.Tpo" -c -o simImage.obj `if test -f 'src/simImage.cc'; then $(CYGPATH_W) 'src/simImage.cc'; else $(CYGPATH_W) '$(srcdir)/src/simImage.cc'; fi`; \
	then mv -f "$(DEPDIR)/simImage.Tpo" "$(DEPDIR)/simImage.Po"; else rm -f "$(DEPDIR)/simImage.Tpo"; exit 1; fi
#	source='src/simImage.cc' object='simImage.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o simImage.obj `if test -f 'src/simImage.cc'; then $(CYGPATH_W) 'src/simImage.cc'; else $(CYGPATH_W) '$(srcdir)/src/simImage.cc'; fi`

myFrame.o: src/myFrame.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT myFrame.o -MD -MP -MF "$(DEPDIR)/myFrame.Tpo" -c -o myFrame.o `test -f 'src/myFrame.cc' || echo '$(srcdir)/'`src/myFrame.cc; \
	then mv -f "$(DEPDIR)/myFrame.Tpo" "$(DEPDIR)/myFrame.Po"; else rm -f "$(DEPDIR)/myFrame.Tpo"; exit 1; fi
#	source='src/myFrame.cc' object='myFrame.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o myFrame.o `test -f 'src/myFrame.cc' || echo '$(srcdir)/'`src/myFrame.cc

myFrame.obj: src/myFrame.cc
	if $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT myFrame.obj -MD -MP -MF "$(DEPDIR)/myFrame.Tpo" -c -o myFrame.obj `if test -f 'src/myFrame.cc'; then $(CYGPATH_W) 'src/myFrame.cc'; else $(CYGPATH_W) '$(srcdir)/src/myFrame.cc'; fi`; \
	then mv -f "$(DEPDIR)/myFrame.Tpo" "$(DEPDIR)/myFrame.Po"; else rm -f "$(DEPDIR)/myFrame.Tpo"; exit 1; fi
#	source='src/myFrame.cc' object='myFrame.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o myFrame.obj `if test -f 'src/myFrame.cc'; then $(CYGPATH_W) 'src/myFrame.cc'; else $(CYGPATH_W) '$(srcdir)/src/myFrame.cc'; fi`
uninstall-info-am:
install-simdockBGSDATA: $(simdockBGS_DATA)
	@$(NORMAL_INSTALL)
	test -z "$(simdockBGSdir)" || $(mkdir_p) "$(DESTDIR)$(simdockBGSdir)"
	@list='$(simdockBGS_DATA)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f=$(am__strip_dir) \
	  echo " $(simdockBGSDATA_INSTALL) '$$d$$p' '$(DESTDIR)$(simdockBGSdir)/$$f'"; \
	  $(simdockBGSDATA_INSTALL) "$$d$$p" "$(DESTDIR)$(simdockBGSdir)/$$f"; \
	done

uninstall-simdockBGSDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(simdockBGS_DATA)'; for p in $$list; do \
	  f=$(am__strip_dir) \
	  echo " rm -f '$(DESTDIR)$(simdockBGSdir)/$$f'"; \
	  rm -f "$(DESTDIR)$(simdockBGSdir)/$$f"; \
	done
install-simdockDESKTOPDATA: $(simdockDESKTOP_DATA)
	@$(NORMAL_INSTALL)
	test -z "$(simdockDESKTOPdir)" || $(mkdir_p) "$(DESTDIR)$(simdockDESKTOPdir)"
	@list='$(simdockDESKTOP_DATA)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f=$(am__strip_dir) \
	  echo " $(simdockDESKTOPDATA_INSTALL) '$$d$$p' '$(DESTDIR)$(simdockDESKTOPdir)/$$f'"; \
	  $(simdockDESKTOPDATA_INSTALL) "$$d$$p" "$(DESTDIR)$(simdockDESKTOPdir)/$$f"; \
	done

uninstall-simdockDESKTOPDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(simdockDESKTOP_DATA)'; for p in $$list; do \
	  f=$(am__strip_dir) \
	  echo " rm -f '$(DESTDIR)$(simdockDESKTOPdir)/$$f'"; \
	  rm -f "$(DESTDIR)$(simdockDESKTOPdir)/$$f"; \
	done
install-simdockICONDATA: $(simdockICON_DATA)
	@$(NORMAL_INSTALL)
	test -z "$(simdockICONdir)" || $(mkdir_p) "$(DESTDIR)$(simdockICONdir)"
	@list='$(simdockICON_DATA)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f=$(am__strip_dir) \
	  echo " $(simdockICONDATA_INSTALL) '$$d$$p' '$(DESTDIR)$(simdockICONdir)/$$f'"; \
	  $(simdockICONDATA_INSTALL) "$$d$$p" "$(DESTDIR)$(simdockICONdir)/$$f"; \
	done

uninstall-simdockICONDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(simdockICON_DATA)'; for p in $$list; do \
	  f=$(am__strip_dir) \
	  echo " rm -f '$(DESTDIR)$(simdockICONdir)/$$f'"; \
	  rm -f "$(DESTDIR)$(simdockICONdir)/$$f"; \
	done

# This directory's subdirectories are mostly independent; you can cd
# into them and run `make' without going through this Makefile.
# To change the values of `make' variables: instead of editing Makefiles,
# (1) if the variable is set in `config.status', edit `config.status'
#     (which will cause the Makefiles to be regenerated when you run `make');
# (2) otherwise, pass the desired values on the `make' command line.
$(RECURSIVE_TARGETS):
	@failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	target=`echo $@ | sed s/-recursive//`; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    dot_seen=yes; \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done; \
	if test "$$dot_seen" = "no"; then \
	  $(MAKE) $(AM_MAKEFLAGS) "$$target-am" || exit 1; \
	fi; test -z "$$fail"

mostlyclean-recursive clean-recursive distclean-recursive \
maintainer-clean-recursive:
	@failcom='exit 1'; \
	for f in x $$MAKEFLAGS; do \
	  case $$f in \
	    *=* | --[!k]*);; \
	    *k*) failcom='fail=yes';; \
	  esac; \
	done; \
	dot_seen=no; \
	case "$@" in \
	  distclean-* | maintainer-clean-*) list='$(DIST_SUBDIRS)' ;; \
	  *) list='$(SUBDIRS)' ;; \
	esac; \
	rev=''; for subdir in $$list; do \
	  if test "$$subdir" = "."; then :; else \
	    rev="$$subdir $$rev"; \
	  fi; \
	done; \
	rev="$$rev ."; \
	target=`echo $@ | sed s/-recursive//`; \
	for subdir in $$rev; do \
	  echo "Making $$target in $$subdir"; \
	  if test "$$subdir" = "."; then \
	    local_target="$$target-am"; \
	  else \
	    local_target="$$target"; \
	  fi; \
	  (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $$local_target) \
	  || eval $$failcom; \
	done && test -z "$$fail"
tags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) tags); \
	done
ctags-recursive:
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  test "$$subdir" = . || (cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) ctags); \
	done

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS: tags-recursive $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	if ($(ETAGS) --etags-include --version) >/dev/null 2>&1; then \
	  include_option=--etags-include; \
	  empty_fix=.; \
	else \
	  include_option=--include; \
	  empty_fix=; \
	fi; \
	list='$(SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test ! -f $$subdir/TAGS || \
	      tags="$$tags $$include_option=$$here/$$subdir/TAGS"; \
	  fi; \
	done; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	if test -z "$(ETAGS_ARGS)$$tags$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	    $$tags $$unique; \
	fi
ctags: CTAGS
CTAGS: ctags-recursive $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(CTAGS_ARGS)$$tags$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$tags $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	mkdir $(distdir)
	@srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's|.|.|g'`; \
	list='$(DISTFILES)'; for file in $$list; do \
	  case $$file in \
	    $(srcdir)/*) file=`echo "$$file" | sed "s|^$$srcdirstrip/||"`;; \
	    $(top_srcdir)/*) file=`echo "$$file" | sed "s|^$$topsrcdirstrip/|$(top_builddir)/|"`;; \
	  esac; \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    dir="/$$dir"; \
	    $(mkdir_p) "$(distdir)$$dir"; \
	  else \
	    dir=''; \
	  fi; \
	  if test -d $$d/$$file; then \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -pR $(srcdir)/$$file $(distdir)$$dir || exit 1; \
	    fi; \
	    cp -pR $$d/$$file $(distdir)$$dir || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
	list='$(DIST_SUBDIRS)'; for subdir in $$list; do \
	  if test "$$subdir" = .; then :; else \
	    test -d "$(distdir)/$$subdir" \
	    || $(mkdir_p) "$(distdir)/$$subdir" \
	    || exit 1; \
	    distdir=`$(am__cd) $(distdir) && pwd`; \
	    top_distdir=`$(am__cd) $(top_distdir) && pwd`; \
	    (cd $$subdir && \
	      $(MAKE) $(AM_MAKEFLAGS) \
	        top_distdir="$$top_distdir" \
	        distdir="$$distdir/$$subdir" \
	        distdir) \
	      || exit 1; \
	  fi; \
	done
	-find $(distdir) -type d ! -perm -777 -exec chmod a+rwx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(SHELL) $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r $(distdir)
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)
dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bunzip2 -c $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gunzip -c $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && cd $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e '1{h;s/./=/g;p;x;}' -e '$${p;x;}'
distuninstallcheck:
	@cd $(distuninstallcheck_dir) \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-recursive
all-am: Makefile $(PROGRAMS) $(DATA) config.h
installdirs: installdirs-recursive
installdirs-am:
	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(simdockBGSdir)" "$(DESTDIR)$(simdockDESKTOPdir)" "$(DESTDIR)$(simdockICONdir)"; do \
	  test -z "$$dir" || $(mkdir_p) "$$dir"; \
	done
install: install-recursive
install-exec: install-exec-recursive
install-data: install-data-recursive
uninstall: uninstall-recursive

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-recursive
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-recursive

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-recursive

dvi-am:

html: html-recursive

info: info-recursive

info-am:

install-data-am: install-simdockBGSDATA install-simdockDESKTOPDATA \
	install-simdockICONDATA

install-exec-am: install-binPROGRAMS

install-info: install-info-recursive

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-recursive
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-recursive

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-recursive

pdf-am:

ps: ps-recursive

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-info-am \
	uninstall-simdockBGSDATA uninstall-simdockDESKTOPDATA \
	uninstall-simdockICONDATA

uninstall-info: uninstall-info-recursive

.PHONY: $(RECURSIVE_TARGETS) CTAGS GTAGS all all-am am--refresh check \
	check-am clean clean-binPROGRAMS clean-generic clean-recursive \
	ctags ctags-recursive dist dist-all dist-bzip2 dist-gzip \
	dist-shar dist-tarZ dist-zip distcheck distclean \
	distclean-compile distclean-generic distclean-hdr \
	distclean-recursive distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-exec install-exec-am install-info \
	install-info-am install-man install-simdockBGSDATA \
	install-simdockDESKTOPDATA install-simdockICONDATA \
	install-strip installcheck installcheck-am installdirs \
	installdirs-am maintainer-clean maintainer-clean-generic \
	maintainer-clean-recursive mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-recursive pdf pdf-am ps ps-am \
	tags tags-recursive uninstall uninstall-am \
	uninstall-binPROGRAMS uninstall-info-am \
	uninstall-simdockBGSDATA uninstall-simdockDESKTOPDATA \
	uninstall-simdockICONDATA

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
