Document: simdock
Title: Debian simdock Manual
Author: <insert document author here>
Abstract: This manual describes what simdock is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/simdock/simdock.sgml.gz

Format: postscript
Files: /usr/share/doc/simdock/simdock.ps.gz

Format: text
Files: /usr/share/doc/simdock/simdock.text.gz

Format: HTML
Index: /usr/share/doc/simdock/html/index.html
Files: /usr/share/doc/simdock/html/*.html

  
